// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIgJxiQBic71onUq4Tw_k_cVBbyooDSII',
    appId: '1:98922274089:web:3edb5af4b3614bd2862b38',
    messagingSenderId: '98922274089',
    projectId: 'login-23a4b',
    authDomain: 'login-23a4b.firebaseapp.com',
    storageBucket: 'login-23a4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1VypDBSlcmxXk2OB4J7ilzOC6HNYx4A',
    appId: '1:98922274089:android:8e6ab719926ead05862b38',
    messagingSenderId: '98922274089',
    projectId: 'login-23a4b',
    storageBucket: 'login-23a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzB9NAAaPZvleJyLZAjiMhE2xYj4qxqLM',
    appId: '1:98922274089:ios:cdcad46201324b2b862b38',
    messagingSenderId: '98922274089',
    projectId: 'login-23a4b',
    storageBucket: 'login-23a4b.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzB9NAAaPZvleJyLZAjiMhE2xYj4qxqLM',
    appId: '1:98922274089:ios:8666db88b3b47ad8862b38',
    messagingSenderId: '98922274089',
    projectId: 'login-23a4b',
    storageBucket: 'login-23a4b.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
